services:
  pgdatabase:
    image: postgres:13
    # environment variables
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    # mapping folder where we have our files systems on the 
    # host machine to a folder in the container: mounting
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

# to add environment variables in docker is with th eflag -e

# to mount volumnes we map the postgres data in the local
# machine folder to the container with -v
# windows needs the full path 
# linux/mac you can $(pwd)/ to substitute the path

# -p to map a port to a port of the container

# 5432 port of the postgres


docker run -it \
  --name postgres-test \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v /e/Documentos/Resources_apuntes/data-engineer-zoomcamp-2024/2_docker_sql/ingesting_data_to_postgres/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
       postgres:13

# pgcli -h localhost -p 5432 -u root -d ny_taxi

docker run -it \
  --name postgres-test \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v /$(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:13
