# docker-compose up or down

# here the creation of a network is not needed, all is inside the same network

services:
  pgdatabase:
    image: postgres:13
    # environment variables
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    # mapping folder where we have our files systems on the 
    # host machine to a folder in the container: mounting
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
